- name: update index file
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify:
    - restart nginx

- name: update config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
